import 'dotenv/config';
import { PrismaClient } from '../src/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({ connectionString: process.env['DATABASE_URL']! });
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const prisma = new PrismaClient({ adapter } as any);

const pacientes = [
  // ── Femenino ──────────────────────────────────────────────────────────────
  {
    nombre: 'María', apellido: 'García López',
    dpi: '1001000000101', fecha_nacimiento: new Date('1988-03-15'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Maestra',
    telefono: '5501-1001', telefono_emergencia: '5501-1002', contacto_emergencia_nombre: 'Pedro García',
    email: 'maria.garcia@gmail.com',
    direccion: 'Zona 3, Antigua Guatemala, Sacatepéquez',
    tipo_sangre: 'O+', alergias: 'Penicilina',
    antecedentes: 'Hipertensión arterial controlada',
    medicamentos: 'Losartán 50mg diario',
    seguro: 'IGSS', numero_afiliacion: 'IGSS-110234',
  },
  {
    nombre: 'Ana', apellido: 'Martínez Flores',
    dpi: '1001000000102', fecha_nacimiento: new Date('1975-07-22'),
    genero: 'femenino' as const, estado_civil: 'Divorciada', ocupacion: 'Contadora',
    telefono: '5502-2002', telefono_emergencia: '5502-2003', contacto_emergencia_nombre: 'Lucía Flores',
    email: 'ana.martinez@yahoo.com',
    direccion: 'Barrio San Sebastián, Antigua Guatemala',
    tipo_sangre: 'A+', alergias: 'Aspirina',
    seguro: 'Seguros G&T', numero_afiliacion: 'GT-009812',
  },
  {
    nombre: 'Carmen', apellido: 'Rodríguez Pérez',
    dpi: '1001000000103', fecha_nacimiento: new Date('1992-11-08'),
    genero: 'femenino' as const, estado_civil: 'Soltera', ocupacion: 'Enfermera',
    telefono: '5503-3003',
    email: 'carmen.rdz@gmail.com',
    direccion: 'Colonia El Naranjo, Antigua Guatemala',
    tipo_sangre: 'B+',
    antecedentes: 'Asma bronquial desde la infancia',
    medicamentos: 'Salbutamol en spray según necesidad',
  },
  {
    nombre: 'Lucía', apellido: 'Hernández Castro',
    dpi: '1001000000104', fecha_nacimiento: new Date('1965-05-30'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Ama de casa',
    telefono: '5504-4004', telefono_emergencia: '5504-4005', contacto_emergencia_nombre: 'Hugo Hernández',
    tipo_sangre: 'O+',
    antecedentes: 'Diabetes mellitus tipo 2, hipotiroidismo',
    medicamentos: 'Metformina 850mg, Levotiroxina 50mcg',
    seguro: 'Mapfre Guatemala', numero_afiliacion: 'MG-445521',
  },
  {
    nombre: 'Patricia', apellido: 'González Morales',
    dpi: '1001000000105', fecha_nacimiento: new Date('1983-09-14'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Abogada',
    telefono: '5505-5005',
    email: 'p.gonzalez@abogados.gt',
    direccion: 'Ciudad Vieja, Sacatepéquez',
    tipo_sangre: 'A+',
    seguro: 'Aseguradora General', numero_afiliacion: 'AG-338876',
  },
  {
    nombre: 'Sandra', apellido: 'López Torres',
    dpi: '1001000000106', fecha_nacimiento: new Date('1990-02-19'),
    genero: 'femenino' as const, estado_civil: 'Unión libre', ocupacion: 'Secretaria',
    telefono: '5506-6006', telefono_emergencia: '5506-6007', contacto_emergencia_nombre: 'Mario López',
    email: 'sandra.lopez@gmail.com',
    tipo_sangre: 'O+',
  },
  {
    nombre: 'Isabel', apellido: 'Castillo Reyes',
    dpi: '1001000000107', fecha_nacimiento: new Date('2001-06-25'),
    genero: 'femenino' as const, estado_civil: 'Soltera', ocupacion: 'Estudiante universitaria',
    telefono: '5507-7007',
    email: 'isa.castillo@estudiantil.umg.edu.gt',
    tipo_sangre: 'A-',
    alergias: 'Ibuprofeno, mariscos',
  },
  {
    nombre: 'Claudia', apellido: 'Flores Estrada',
    dpi: '1001000000108', fecha_nacimiento: new Date('1978-12-03'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Farmacéutica',
    telefono: '5508-8008',
    direccion: 'Aldea San Pedro Las Huertas, Antigua Guatemala',
    tipo_sangre: 'B+',
    antecedentes: 'Artritis reumatoide',
    medicamentos: 'Metotrexato 15mg semanal',
    seguro: 'IGSS', numero_afiliacion: 'IGSS-220445',
  },
  {
    nombre: 'Sofía', apellido: 'Ramírez Jiménez',
    dpi: '1001000000109', fecha_nacimiento: new Date('1995-04-17'),
    genero: 'femenino' as const, estado_civil: 'Soltera', ocupacion: 'Diseñadora gráfica',
    telefono: '5509-9009',
    email: 'sofia.rmz@gmail.com',
    tipo_sangre: 'O+',
  },
  {
    nombre: 'Elena', apellido: 'Morales Cruz',
    dpi: '1001000000110', fecha_nacimiento: new Date('1960-10-28'),
    genero: 'femenino' as const, estado_civil: 'Viuda', ocupacion: 'Comerciante',
    telefono: '5510-0010', telefono_emergencia: '5510-0011', contacto_emergencia_nombre: 'Ana Cruz (hija)',
    direccion: 'San Miguel Dueñas, Sacatepéquez',
    tipo_sangre: 'AB+',
    antecedentes: 'Cardiopatía isquémica, hipertensión arterial',
    medicamentos: 'Ácido acetilsalicílico 100mg, Enalapril 10mg',
    seguro: 'Seguros Universales', numero_afiliacion: 'SU-778823',
  },
  {
    nombre: 'Marta', apellido: 'Pérez Barrios',
    dpi: '1001000000111', fecha_nacimiento: new Date('1987-08-09'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Nutricionista',
    telefono: '5511-1011',
    email: 'marta.perez@nutricion.com',
    tipo_sangre: 'A+',
  },
  {
    nombre: 'Julia', apellido: 'Torres Alvarado',
    dpi: '1001000000112', fecha_nacimiento: new Date('1972-01-16'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Profesora universitaria',
    telefono: '5512-2012', telefono_emergencia: '5512-2013', contacto_emergencia_nombre: 'Roberto Torres',
    email: 'j.torres@umg.edu.gt',
    direccion: 'Zona 1, Antigua Guatemala',
    tipo_sangre: 'O+',
    antecedentes: 'Gastritis crónica',
    medicamentos: 'Omeprazol 20mg',
  },
  {
    nombre: 'Laura', apellido: 'Castro Mendoza',
    dpi: '1001000000113', fecha_nacimiento: new Date('1999-05-21'),
    genero: 'femenino' as const, estado_civil: 'Soltera', ocupacion: 'Estudiante',
    telefono: '5513-3013',
    tipo_sangre: 'B+',
    alergias: 'Polen, polvo',
    antecedentes: 'Rinitis alérgica crónica',
  },
  {
    nombre: 'Alicia', apellido: 'Ortega Orellana',
    dpi: '1001000000114', fecha_nacimiento: new Date('1958-07-04'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Jubilada',
    telefono: '5514-4014', telefono_emergencia: '5514-4015', contacto_emergencia_nombre: 'Carlos Ortega',
    tipo_sangre: 'O+',
    antecedentes: 'Osteoporosis, hipertensión arterial',
    medicamentos: 'Calcio 1200mg, Vitamina D, Amlodipino 5mg',
    seguro: 'IGSS', numero_afiliacion: 'IGSS-004567',
  },
  {
    nombre: 'Gabriela', apellido: 'Sandoval Aguilar',
    dpi: '1001000000115', fecha_nacimiento: new Date('1994-03-29'),
    genero: 'femenino' as const, estado_civil: 'Unión libre', ocupacion: 'Cosmetóloga',
    telefono: '5515-5015',
    email: 'gabi.sandoval@gmail.com',
    tipo_sangre: 'A+',
  },
  {
    nombre: 'Verónica', apellido: 'Fuentes Salazar',
    dpi: '1001000000116', fecha_nacimiento: new Date('1969-11-13'),
    genero: 'femenino' as const, estado_civil: 'Divorciada', ocupacion: 'Economista',
    telefono: '5516-6016',
    direccion: 'Alotenango, Sacatepéquez',
    tipo_sangre: 'O-',
    alergias: 'Látex, sulfas',
    seguro: 'Seguros Agromercantil', numero_afiliacion: 'SAM-123456',
  },
  {
    nombre: 'Diana', apellido: 'Jiménez Monzón',
    dpi: '1001000000117', fecha_nacimiento: new Date('1986-06-07'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Periodista',
    telefono: '5517-7017', telefono_emergencia: '5517-7018', contacto_emergencia_nombre: 'Luis Jiménez',
    email: 'diana.jimenez@prensalibre.com',
    tipo_sangre: 'AB+',
  },
  {
    nombre: 'Fernanda', apellido: 'Reyes García',
    dpi: '1001000000118', fecha_nacimiento: new Date('2003-09-02'),
    genero: 'femenino' as const, estado_civil: 'Soltera', ocupacion: 'Estudiante de preparatoria',
    telefono: '5518-8018',
    tipo_sangre: 'A+',
  },
  {
    nombre: 'Beatriz', apellido: 'Cruz Vargas',
    dpi: '1001000000119', fecha_nacimiento: new Date('1971-04-11'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Ingeniera civil',
    telefono: '5519-9019',
    email: 'beatriz.cruz@ingenieria.gt',
    tipo_sangre: 'B-',
    antecedentes: 'Epilepsia controlada',
    medicamentos: 'Ácido valproico 500mg',
    seguro: 'Seguros G&T', numero_afiliacion: 'GT-556677',
  },
  {
    nombre: 'Andrea', apellido: 'Vargas Chávez',
    dpi: '1001000000120', fecha_nacimiento: new Date('1997-12-18'),
    genero: 'femenino' as const, estado_civil: 'Soltera', ocupacion: 'Fisioterapeuta',
    telefono: '5520-0020',
    email: 'andrea.vargas@fisio.gt',
    tipo_sangre: 'O+',
  },
  {
    nombre: 'Jessica', apellido: 'Chávez Estrada',
    dpi: '1001000000121', fecha_nacimiento: new Date('1984-08-26'),
    genero: 'femenino' as const, estado_civil: 'Unión libre', ocupacion: 'Administradora de empresas',
    telefono: '5521-1021', telefono_emergencia: '5521-1022', contacto_emergencia_nombre: 'Rodrigo Estrada',
    tipo_sangre: 'A+',
    alergias: 'Amoxicilina',
  },
  {
    nombre: 'Karla', apellido: 'Estrada Cifuentes',
    dpi: '1001000000122', fecha_nacimiento: new Date('1991-02-05'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Arquitecta',
    telefono: '5522-2022',
    email: 'karla.estrada@arq.gt',
    direccion: 'San Juan del Obispo, Sacatepéquez',
    tipo_sangre: 'O+',
  },
  {
    nombre: 'Mónica', apellido: 'Cifuentes López',
    dpi: '1001000000123', fecha_nacimiento: new Date('1976-10-09'),
    genero: 'femenino' as const, estado_civil: 'Divorciada', ocupacion: 'Técnica en laboratorio',
    telefono: '5523-3023',
    tipo_sangre: 'B+',
    antecedentes: 'Hipotiroidismo',
    medicamentos: 'Levotiroxina 75mcg en ayunas',
    seguro: 'IGSS', numero_afiliacion: 'IGSS-332211',
  },
  {
    nombre: 'Norma', apellido: 'Alvarado Fuentes',
    dpi: '1001000000124', fecha_nacimiento: new Date('1963-03-24'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Agricultora',
    telefono: '5524-4024', telefono_emergencia: '5524-4025', contacto_emergencia_nombre: 'Héctor Alvarado',
    direccion: 'Aldea El Hato, Antigua Guatemala',
    tipo_sangre: 'O+',
    antecedentes: 'Diabetes mellitus tipo 2',
    medicamentos: 'Glibenclamida 5mg, Metformina 500mg',
  },
  {
    nombre: 'Rebeca', apellido: 'Mendoza Castillo',
    dpi: '1001000000125', fecha_nacimiento: new Date('2005-07-31'),
    genero: 'femenino' as const, estado_civil: 'Soltera', ocupacion: 'Estudiante',
    telefono: '5525-5025',
    tipo_sangre: 'A+',
  },
  {
    nombre: 'Silvia', apellido: 'Orellana Torres',
    dpi: '1001000000126', fecha_nacimiento: new Date('1953-01-17'),
    genero: 'femenino' as const, estado_civil: 'Viuda', ocupacion: 'Jubilada',
    telefono: '5526-6026', telefono_emergencia: '5526-6027', contacto_emergencia_nombre: 'Mario Orellana (hijo)',
    tipo_sangre: 'AB+',
    antecedentes: 'Insuficiencia renal crónica estadio 3, hipertensión arterial',
    medicamentos: 'Furosemida 40mg, Losartán 100mg, Eritropoyetina',
    seguro: 'Seguros Universales', numero_afiliacion: 'SU-001122',
    observaciones: 'Paciente con dieta restringida en proteínas y potasio',
  },
  {
    nombre: 'Miriam', apellido: 'Aguilar Ramírez',
    dpi: '1001000000127', fecha_nacimiento: new Date('1988-11-22'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Psicóloga',
    telefono: '5527-7027',
    email: 'miriam.aguilar@psico.gt',
    tipo_sangre: 'O+',
  },
  {
    nombre: 'Yolanda', apellido: 'Salazar Cruz',
    dpi: '1001000000128', fecha_nacimiento: new Date('1967-05-06'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Modista',
    telefono: '5528-8028',
    tipo_sangre: 'A+',
    alergias: 'Diclofenaco',
  },
  {
    nombre: 'Teresa', apellido: 'Monzón González',
    dpi: '1001000000129', fecha_nacimiento: new Date('1945-09-10'),
    genero: 'femenino' as const, estado_civil: 'Viuda', ocupacion: 'Jubilada',
    telefono: '5529-9029', telefono_emergencia: '5529-9030', contacto_emergencia_nombre: 'Silvia Monzón (hija)',
    tipo_sangre: 'O+',
    antecedentes: 'Cardiopatía isquémica, fibrilación auricular, obesidad grado II',
    medicamentos: 'Warfarina 5mg, Metoprolol 50mg, Furosemida 20mg',
    seguro: 'IGSS', numero_afiliacion: 'IGSS-000023',
    observaciones: 'Requiere monitoreo mensual de INR',
  },
  {
    nombre: 'Blanca', apellido: 'López Ramos',
    dpi: '1001000000130', fecha_nacimiento: new Date('1980-04-13'),
    genero: 'femenino' as const, estado_civil: 'Casada', ocupacion: 'Cocinera',
    telefono: '5530-0030',
    tipo_sangre: 'B+',
  },

  // ── Masculino ─────────────────────────────────────────────────────────────
  {
    nombre: 'José', apellido: 'González García',
    dpi: '1001000000131', fecha_nacimiento: new Date('1982-06-28'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Mecánico',
    telefono: '5531-1031', telefono_emergencia: '5531-1032', contacto_emergencia_nombre: 'Carmen García (esposa)',
    tipo_sangre: 'O+',
    seguro: 'IGSS', numero_afiliacion: 'IGSS-456789',
  },
  {
    nombre: 'Juan', apellido: 'López Martínez',
    dpi: '1001000000132', fecha_nacimiento: new Date('1971-03-05'),
    genero: 'masculino' as const, estado_civil: 'Divorciado', ocupacion: 'Albañil',
    telefono: '5532-2032',
    tipo_sangre: 'A+',
    antecedentes: 'Hipertensión arterial',
    medicamentos: 'Enalapril 20mg',
  },
  {
    nombre: 'Carlos', apellido: 'Martínez Hernández',
    dpi: '1001000000133', fecha_nacimiento: new Date('1990-10-17'),
    genero: 'masculino' as const, estado_civil: 'Soltero', ocupacion: 'Programador',
    telefono: '5533-3033',
    email: 'carlos.mtz@gmail.com',
    tipo_sangre: 'B+',
    alergias: 'Maní',
  },
  {
    nombre: 'Luis', apellido: 'Hernández Pérez',
    dpi: '1001000000134', fecha_nacimiento: new Date('1978-01-23'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Piloto de bus',
    telefono: '5534-4034', telefono_emergencia: '5534-4035', contacto_emergencia_nombre: 'Rosa Pérez (esposa)',
    tipo_sangre: 'O+',
    antecedentes: 'Diabetes mellitus tipo 2, sobrepeso',
    medicamentos: 'Metformina 1000mg, Sitagliptina 50mg',
    seguro: 'IGSS', numero_afiliacion: 'IGSS-567890',
  },
  {
    nombre: 'Pedro', apellido: 'Pérez Rodríguez',
    dpi: '1001000000135', fecha_nacimiento: new Date('1965-08-04'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Agricultor',
    telefono: '5535-5035',
    direccion: 'San Miguel Dueñas, Sacatepéquez',
    tipo_sangre: 'A+',
    alergias: 'Sulfas, metamizol',
  },
  {
    nombre: 'Miguel', apellido: 'Rodríguez Ramírez',
    dpi: '1001000000136', fecha_nacimiento: new Date('1993-12-30'),
    genero: 'masculino' as const, estado_civil: 'Soltero', ocupacion: 'Técnico electricista',
    telefono: '5536-6036',
    email: 'miguel.rdz@gmail.com',
    tipo_sangre: 'O+',
  },
  {
    nombre: 'Roberto', apellido: 'Ramírez Flores',
    dpi: '1001000000137', fecha_nacimiento: new Date('1958-05-19'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Jubilado',
    telefono: '5537-7037', telefono_emergencia: '5537-7038', contacto_emergencia_nombre: 'Elena Flores (esposa)',
    tipo_sangre: 'AB+',
    antecedentes: 'Cardiopatía isquémica, hipercolesterolemia',
    medicamentos: 'Atorvastatina 40mg, Ácido acetilsalicílico 100mg, Bisoprolol 5mg',
    seguro: 'Seguros G&T', numero_afiliacion: 'GT-221133',
    observaciones: 'Antecedente de infarto al miocardio en 2019',
  },
  {
    nombre: 'Fernando', apellido: 'Flores Torres',
    dpi: '1001000000138', fecha_nacimiento: new Date('1986-07-08'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Contador',
    telefono: '5538-8038',
    email: 'f.flores@contabilidad.gt',
    tipo_sangre: 'A+',
    seguro: 'Aseguradora General', numero_afiliacion: 'AG-665544',
  },
  {
    nombre: 'Eduardo', apellido: 'Torres Castillo',
    dpi: '1001000000139', fecha_nacimiento: new Date('2000-02-14'),
    genero: 'masculino' as const, estado_civil: 'Soltero', ocupacion: 'Estudiante universitario',
    telefono: '5539-9039',
    tipo_sangre: 'O+',
    alergias: 'Látex',
  },
  {
    nombre: 'Alejandro', apellido: 'Castillo Morales',
    dpi: '1001000000140', fecha_nacimiento: new Date('1975-11-27'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Dentista',
    telefono: '5540-0040', telefono_emergencia: '5540-0041', contacto_emergencia_nombre: 'Isabel Morales (esposa)',
    email: 'dr.castillo@dental.gt',
    tipo_sangre: 'B+',
    seguro: 'Mapfre Guatemala', numero_afiliacion: 'MG-887766',
  },
  {
    nombre: 'Manuel', apellido: 'Morales Castro',
    dpi: '1001000000141', fecha_nacimiento: new Date('1969-04-01'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Carpintero',
    telefono: '5541-1041',
    direccion: 'Barrio La Concepción, Antigua Guatemala',
    tipo_sangre: 'O+',
    antecedentes: 'Lumbalgia crónica',
    observaciones: 'Trabajo físico intenso, requiere evaluación ergonómica',
  },
  {
    nombre: 'Ricardo', apellido: 'Castro Ortega',
    dpi: '1001000000142', fecha_nacimiento: new Date('1988-09-15'),
    genero: 'masculino' as const, estado_civil: 'Unión libre', ocupacion: 'Chef',
    telefono: '5542-2042',
    email: 'ricardo.castro@restaurante.gt',
    tipo_sangre: 'A+',
  },
  {
    nombre: 'Diego', apellido: 'Ortega Sandoval',
    dpi: '1001000000143', fecha_nacimiento: new Date('1996-01-09'),
    genero: 'masculino' as const, estado_civil: 'Soltero', ocupacion: 'Fotógrafo',
    telefono: '5543-3043',
    email: 'diego.ortega@foto.gt',
    tipo_sangre: 'O+',
    alergias: 'Penicilina, amoxicilina',
  },
  {
    nombre: 'Pablo', apellido: 'Sandoval Fuentes',
    dpi: '1001000000144', fecha_nacimiento: new Date('1961-06-18'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Veterinario',
    telefono: '5544-4044', telefono_emergencia: '5544-4045', contacto_emergencia_nombre: 'Norma Fuentes (esposa)',
    tipo_sangre: 'A+',
    antecedentes: 'Hipertensión arterial, gota',
    medicamentos: 'Amlodipino 10mg, Alopurinol 300mg',
    seguro: 'IGSS', numero_afiliacion: 'IGSS-234567',
  },
  {
    nombre: 'Sergio', apellido: 'Fuentes Jiménez',
    dpi: '1001000000145', fecha_nacimiento: new Date('1984-03-22'),
    genero: 'masculino' as const, estado_civil: 'Divorciado', ocupacion: 'Administrador de empresas',
    telefono: '5545-5045',
    tipo_sangre: 'B+',
  },
  {
    nombre: 'Javier', apellido: 'Jiménez Reyes',
    dpi: '1001000000146', fecha_nacimiento: new Date('1979-08-13'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Policía',
    telefono: '5546-6046', telefono_emergencia: '5546-6047', contacto_emergencia_nombre: 'Patricia Reyes (esposa)',
    tipo_sangre: 'O+',
    seguro: 'IGSS', numero_afiliacion: 'IGSS-789012',
    antecedentes: 'Estrés laboral crónico, gastritis',
    medicamentos: 'Omeprazol 20mg',
  },
  {
    nombre: 'Mario', apellido: 'Reyes Cruz',
    dpi: '1001000000147', fecha_nacimiento: new Date('1992-05-07'),
    genero: 'masculino' as const, estado_civil: 'Soltero', ocupacion: 'Músico',
    telefono: '5547-7047',
    email: 'mario.reyes@music.gt',
    tipo_sangre: 'AB-',
  },
  {
    nombre: 'Andrés', apellido: 'Cruz Vargas',
    dpi: '1001000000148', fecha_nacimiento: new Date('2004-10-29'),
    genero: 'masculino' as const, estado_civil: 'Soltero', ocupacion: 'Estudiante',
    telefono: '5548-8048',
    tipo_sangre: 'O+',
  },
  {
    nombre: 'Héctor', apellido: 'Vargas Chávez',
    dpi: '1001000000149', fecha_nacimiento: new Date('1956-12-31'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Jubilado',
    telefono: '5549-9049', telefono_emergencia: '5549-9050', contacto_emergencia_nombre: 'Beatriz Chávez (esposa)',
    tipo_sangre: 'A+',
    antecedentes: 'Enfisema pulmonar, diabetes mellitus tipo 2, hipertensión arterial',
    medicamentos: 'Insulina NPH 20UI, Metformina 850mg, Enalapril 10mg, Tiotropio inhalado',
    seguro: 'Seguros Universales', numero_afiliacion: 'SU-445566',
    observaciones: 'Fumador durante 30 años, dejó el hábito en 2010',
  },
  {
    nombre: 'Ernesto', apellido: 'Chávez Estrada',
    dpi: '1001000000150', fecha_nacimiento: new Date('1973-07-16'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Ingeniero industrial',
    telefono: '5550-0050',
    email: 'ernesto.chavez@industria.gt',
    tipo_sangre: 'O+',
    alergias: 'Ibuprofeno',
    seguro: 'Aseguradora General', numero_afiliacion: 'AG-112233',
  },
  {
    nombre: 'Oscar', apellido: 'Estrada Cifuentes',
    dpi: '1001000000151', fecha_nacimiento: new Date('1987-02-24'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Maestro de primaria',
    telefono: '5551-1051', telefono_emergencia: '5551-1052', contacto_emergencia_nombre: 'Karla Cifuentes (esposa)',
    tipo_sangre: 'B+',
    antecedentes: 'Depresión mayor en remisión',
    medicamentos: 'Sertralina 50mg',
  },
  {
    nombre: 'Rodolfo', apellido: 'Cifuentes Barrios',
    dpi: '1001000000152', fecha_nacimiento: new Date('1967-09-20'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Comerciante',
    telefono: '5552-2052',
    tipo_sangre: 'O+',
  },
  {
    nombre: 'Víctor', apellido: 'Barrios Alvarado',
    dpi: '1001000000153', fecha_nacimiento: new Date('1995-11-11'),
    genero: 'masculino' as const, estado_civil: 'Soltero', ocupacion: 'Técnico automotriz',
    telefono: '5553-3053',
    email: 'victor.barrios@gmail.com',
    tipo_sangre: 'A+',
  },
  {
    nombre: 'Jorge', apellido: 'Alvarado Mendoza',
    dpi: '1001000000154', fecha_nacimiento: new Date('1944-04-06'),
    genero: 'masculino' as const, estado_civil: 'Viudo', ocupacion: 'Jubilado',
    telefono: '5554-4054', telefono_emergencia: '5554-4055', contacto_emergencia_nombre: 'Rosa Alvarado (hija)',
    tipo_sangre: 'O+',
    antecedentes: 'Insuficiencia cardíaca congestiva, fibrilación auricular, diabetes mellitus tipo 2',
    medicamentos: 'Digoxina 0.125mg, Furosemida 40mg, Carvedilol 6.25mg, Warfarina 2.5mg, Insulina',
    seguro: 'IGSS', numero_afiliacion: 'IGSS-000001',
    observaciones: 'Paciente de alta complejidad, requiere seguimiento cardiológico mensual y control de coagulación',
  },
  {
    nombre: 'David', apellido: 'Mendoza Orellana',
    dpi: '1001000000155', fecha_nacimiento: new Date('1981-06-03'),
    genero: 'masculino' as const, estado_civil: 'Casado', ocupacion: 'Abogado',
    telefono: '5555-5055',
    email: 'david.mendoza@ley.gt',
    tipo_sangre: 'A+',
    seguro: 'Mapfre Guatemala', numero_afiliacion: 'MG-998877',
  },
  {
    nombre: 'Raúl', apellido: 'Orellana Aguilar',
    dpi: '1001000000156', fecha_nacimiento: new Date('2007-03-28'),
    genero: 'masculino' as const, estado_civil: 'Soltero', ocupacion: 'Estudiante de secundaria',
    telefono: '5556-6056',
    tipo_sangre: 'O+',
    alergias: 'Mariscos',
  },
];

async function main() {
  let creados = 0;

  for (const p of pacientes) {
    const existing = await prisma.pacientes.findUnique({ where: { dpi: p.dpi } });
    if (existing) {
      console.log(`Ya existe DPI ${p.dpi} (${p.nombre} ${p.apellido}) — omitido`);
      continue;
    }

    await prisma.pacientes.create({ data: p });
    console.log(`Creado: ${p.nombre} ${p.apellido}`);
    creados++;
  }

  console.log(`\nListo: ${creados} pacientes registrados.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
